---
title: "dcm_figures"
author: "Katherine Lauck"
date: "2024-05-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = FALSE,warning = FALSE,message = FALSE)
library(tidyverse)
require(ggeffects)
require(lme4)
require(viridis)
library(car)
library(gt)
g <- read_rds("../data/growth.rds")
c_f <- read_rds('../data/cort_with_id.rds') %>%
  filter(Age %in% c("ASY","SY","AHY"),Sex == "F")
```

## P1

```{r}
dummy_fcond <- seq(from = min(c_f$condition,na.rm = TRUE),
                   to = max(c_f$condition,na.rm = TRUE),
                   length.out = 100)
dummy_c <- seq(from = 1, to = 10, length.out = 100)

(p1 <- ggplot(mapping = aes(x = dummy_fcond,y = dummy_c)) +
  geom_smooth(color = "#35b779",linewidth = 2) +
  theme_classic() +
  ylab("Elevated - baseline cort (\U00B5g/mL)") +
  xlab("Adult female body condition at nestling hatch") +
    theme(text = element_text(size = 16)))

ggsave("../figures/ch3prediction1.png",p1,width = 6,height = 4)
```

## P2

## P1

```{r}
dummy_tri <- tibble(high = seq(from = 1, to = 10, length.out = 100),
                    low = seq(from = 1, to = 5, length.out = 100)) %>%
  pivot_longer(cols = everything(),names_to = "condition",values_to = "triglycerides")
dummy_c <- tibble(high = seq(from = 1, to = 10, length.out = 100),
                  low = seq(from = 1, to = 10, length.out = 100)) %>%
  pivot_longer(cols = everything(),names_to = "condition",values_to = "cort")

fig_data <- bind_cols(dummy_tri,dummy_c)

(p1 <- ggplot(data = fig_data,mapping = aes(x = cort,y = triglycerides,color = condition...1)) +
  geom_smooth(linewidth = 2) +
  theme_classic() +
    theme(legend.position = c(.2, .8)) +
  ylab("Elevated - baseline triglycerides") +
  xlab("Elevated - baseline cort (\U00B5g/mL)") +
    theme(text = element_text(size = 16)) +
    scale_color_manual(values=c("#35b779", "#31688e")) +
  labs(title = element_blank(),color = "Body condition"))

ggsave("../figures/ch3prediction2.png",p1,width = 6,height = 4)
```

## P3

```{r}
dummy_heat <- tibble(high = seq(from = 20, to = 40, length.out = 100),
                    low = seq(from = 20, to = 40, length.out = 100)) %>%
  pivot_longer(cols = everything(),names_to = "condition",values_to = "temp")
dummy_prov <- tibble(high = rep(10,times = 100),
                  low = seq(from = 10, to = 2, length.out = 100)) %>%
  pivot_longer(cols = everything(),names_to = "condition",values_to = "provis")

fig_data <- bind_cols(dummy_heat,dummy_prov)

(p1 <- ggplot(data = fig_data,mapping = aes(x = temp,y = provis,color = condition...1)) +
  geom_smooth(linewidth = 2) +
  theme_classic() +
    theme(legend.position = c(.2, .2)) +
  ylab("Provisioning rate and/or nestling growth") +
  xlab("Maximum temperature (\u00B0C)") +
    theme(text = element_text(size = 14),
          axis.text.y=element_blank(), 
      axis.ticks.y=element_blank()) +
    scale_color_manual(values=c("#35b779", "#31688e")) +
  labs(title = element_blank(),color = "Body condition"))

ggsave("../figures/ch3prediction3.png",p1,width = 6,height = 4)
```


## humidity interaction

```{r}
meanI_WEBL_humint <- lmerTest::lmer(gweight_scaled ~ meanmaxtempI_scaled * habitat * meanh_scaled + poly(meanmintempI_scaled,2) * habitat + age + juliandate_scaled + (1|year) + (1|site/attempt_id),data = filter(g,Species == "WEBL",
                                                                                                                                                                                           !is.na(meanmaxtempI),
                                                                                                                                                                        !is.na(meanh)) %>%
                                    mutate(across(c(gweight,meanmaxtempI,meanmintempI,juliandate,brood_size,meanh),
                                                  ~ scale(.x)[,1],
                                                  .names = "{.col}_scaled"),
                                           meanmaxtempI_scaled_sq = meanmaxtempI_scaled * meanmaxtempI_scaled))

(p <- ggpredict(meanI_WEBL_humint,terms = c("meanmaxtempI_scaled [all]","meanh_scaled","habitat")) %>% 
    # mutate(group = recode_factor(group,`-0.98`="-1 SD",`-0.02` = "Mean",`0.94`="+1 SD")) %>%
    plot(line.size = 1.5,alpha = .2) +
    theme_classic() +
    xlab("Maximum temperature (\u00B0C)") +
    ylab("Nestling growth (g/day)") +
    labs(title = element_blank(),color = "Humidity") +
    #guides(color = guide_legend(reverse = TRUE)) +
   ggtitle("Humidity preliminary results: WEBL") +
    #binned_scale(aesthetics = "color",palette = function(x) c("#f0f921", "#cc4778","#0d0887"), labels = c(NA,"-1 SD", "Mean", "+1 SD",NA,NA)) +
    scale_color_manual(labels = c("Low","Mean","High"),values = c("#f0f921", "#cc4778","#0d0887")) +
    scale_fill_manual(labels = c("Low","Mean","High"),values = c("#f0f921", "#cc4778","#0d0887")) +
    theme(text = element_text(size = 14)))

model <- meanI_WEBL_humint

mround <- function(x,base){
	base*round(x/base)
}

unscale_x <- function(axis_break) {
  if(is.na(axis_break)) {
    return(NA)
  } else {
    sd_x = getData(model) %>% pull(meanmaxtempI) %>% sd(na.rm = TRUE)
    mean_x = getData(model) %>% pull(meanmaxtempI) %>% mean(na.rm = TRUE)
    out <- (axis_break * sd_x + mean_x) %>% mround(5)
  }
}

unscale_y <- function(axis_break) {
  if(is.na(axis_break)) {
    return(0)
  } else {
    sd_y = getData(model) %>% pull(gweight) %>% sd(na.rm = TRUE)
    mean_y = getData(model) %>% pull(gweight) %>% mean(na.rm = TRUE)
    out <- (axis_break * sd_y + mean_y) %>% round(digits = 1)
  }
}

(p_rescaled <- p +
   scale_x_continuous(labels = map(layer_scales(p)$x$break_positions(),unscale_x) %>% unlist())  +
    scale_y_continuous(labels = map(layer_scales(p)$y$break_positions(),unscale_y) %>% unlist()))


ggsave("../figures/ch2q5.png",p_rescaled,width = 6,height = 4)



```

## C3H1

```{r}

webl_deltacortbycond <- lmerTest::lmer(log(delta_cort) ~ condition_scaled + brood_size +
                                         #meanmaxtempI_scaled * habitat + 
                                         #poly(meanmintempI_scaled,2) * habitat +
                                         #poly(meanmaxtempI_scaled,2,raw = TRUE) * meanh_scaled +
                                          juliandate_scaled + (1|year) +
                                         (1|site),
                                       data = (filter(c_f,Species == "WEBL",
                                                     # !is.nan(cort_s1),
                                                     !is.na(meanmaxtempI),
                                                     !is.na(mean_s1),
                                                     !is.na(mean_s2)) %>%
                                    mutate(across(c(meanmaxtempI,
                                                    #meanmintempI,
                                                    meanh,
                                                    condition,
                                                    juliandate),
                                                  ~ scale(.x)[,1],
                                                  .names = "{.col}_scaled"),
                                           meanmaxtempI_scaled_sq = 
                                             meanmaxtempI_scaled * meanmaxtempI_scaled,
                                           condition_scaled = scale(log(condition))[,1],
                                           delta_cort = mean_s2-mean_s1)))

model <- webl_deltacortbycond

(p <- ggpredict(model,terms = "condition_scaled") %>% plot(line.size = 1.5,colors = "#35b779") +
    theme_classic() +
    xlab("Adult female condition (mass/tarsus)") +
    ylab("Elevated - baseline cort")+
    ggtitle("Condition preliminary results: WEBL"))

mround <- function(x,base){
	base*round(x/base)
}

unscale_x <- function(axis_break) {
  if(is.na(axis_break)) {
    return(NA)
  } else {
    sd_x = getData(model) %>% pull(condition) %>% log() %>% sd(na.rm = TRUE)
    mean_x = getData(model) %>% pull(condition) %>% log() %>% mean(na.rm = TRUE)
    out <- (axis_break * sd_x + mean_x) %>% exp() %>% round(2)
  }
}

unscale_y <- function(axis_break) {
  if(is.na(axis_break)) {
    return(0)
  } else {
    sd_y = getData(model) %>% pull(cort_s1) %>% sd(na.rm = TRUE)
    mean_y = getData(model) %>% pull(cort_s1) %>% mean(na.rm = TRUE)
    out <- (axis_break * sd_y + mean_y) %>% round(digits = 1)
  }
}

(p_rescaled <- p +
   scale_x_continuous(labels = map(layer_scales(p)$x$break_positions(),unscale_x) %>% unlist()))#  +
   # scale_y_continuous(labels = map(layer_scales(p)$y$break_positions(),unscale_y) %>% unlist()))

ggsave("../figures/ch3h1_results.png")

```

## C3H3

```{r}

webl_growthbyheat <- lmerTest::lmer(log(gweight) ~ condition_mother_scaled + brood_size +
                                         poly(meanmaxtempI_scaled,2) * habitat + 
                                         poly(meanmintempI_scaled,2) * habitat +
                                         #poly(meanmaxtempI_scaled,2,raw = TRUE) * meanh_scaled +
                                          juliandate_scaled + (1|year) +
                                         (1|site/attempt_id),
                                       data = (filter(g,Species == "WEBL",
                                                     # !is.nan(cort_s1),
                                                     !is.na(meanmaxtempI),
                                                     !is.na(condition_mother),
                                                     !is.na(gweight),
                                                     gweight>0,
                                                     occasion == 2) %>%
                                    mutate(across(c(meanmaxtempI,
                                                    meanmintempI,
                                                    meanh,
                                                    condition_mother,
                                                    juliandate),
                                                  ~ scale(.x)[,1],
                                                  .names = "{.col}_scaled"),
                                           meanmaxtempI_scaled_sq = 
                                             meanmaxtempI_scaled * meanmaxtempI_scaled,
                                           condition_mother_scaled = scale(log(condition_mother))[,1])))


model <- webl_growthbyheat

d <- getData(model)

mean(d$condition_mother_scaled) - sd(d$condition_mother_scaled)

(p <- ggpredict(model,terms = c("meanmaxtempI_scaled[all]","condition_mother_scaled[-1,1]")) %>% plot(line.size = 1.5) +
    theme_classic() +
    xlab("Mean maximum temperature (\u00B0C)") +
    ylab("Nestling growth (g/day)")+
    labs(title = element_blank(),color = "\u2640 condition") +
    scale_color_manual(labels = c("Low","High"),values = c("#35b779","#31688e")) +
    scale_fill_manual(labels = c("Low","High"),values = c("#35b779","#31688e")) +
    ggtitle("Growth with condition preliminary results: WEBL") +
    ylim(0,3))

mround <- function(x,base){
	base*round(x/base)
}

unscale_x <- function(axis_break) {
  if(is.na(axis_break)) {
    return(NA)
  } else {
    sd_x = getData(model) %>% pull(meanmaxtempI) %>% sd(na.rm = TRUE)
    mean_x = getData(model) %>% pull(meanmaxtempI) %>% mean(na.rm = TRUE)
    out <- (axis_break * sd_x + mean_x) %>% mround(5)
  }
}

unscale_y <- function(axis_break) {
  if(is.na(axis_break)) {
    return(0)
  } else {
    sd_y = getData(model) %>% pull(gweight) %>% sd(na.rm = TRUE)
    mean_y = getData(model) %>% pull(gweight) %>% mean(na.rm = TRUE)
    out <- (axis_break * sd_y + mean_y) %>% round(digits = 1)
  }
}

(p_rescaled <- p +
   scale_x_continuous(labels = map(layer_scales(p)$x$break_positions(),unscale_x) %>% unlist()))  #+
   #scale_y_continuous(labels = map(layer_scales(p)$y$break_positions(),unscale_y) %>% unlist()))

ggsave("../figures/ch3h3_results.png")

```
