# Publication figures
# Requires: data/models_*.RData (generated by model_*.R scripts)

library(tidyverse)
library(ggplot2)
library(egg)
library(ggeffects)
library(viridis)
library(scales)
library(dagitty)
library(ggdag)
library(lubridate)


## --- Growth figures ---

load("data/models_growth.RData")

# Fig S5: WEBL + TRES growth supplement (p_full from RData is the fig6 assembly)
ggsave("figures/fig6_growth_by_temp_hab.png", p_full, width = 6.25, height = 8)

# Fig 2: WEBL + TRES growth ~ max temp x habitat
ggplot_build(fig2_webl)$layout$panel_scales_y
ggplot_build(fig2_tres)$layout$panel_scales_y
(p_full <- ggarrange(fig2_webl + theme(text = element_text(size = 12), axis.title.x = element_blank()),
                     fig2_tres + ylim(-1.09, 3.42) + theme(axis.text.y = element_blank(),
                                                            axis.ticks.y = element_blank(),
                                                            text = element_text(size = 12),
                                                            axis.title.y = element_blank(),
                                                            axis.title.x = element_text(hjust = 2.8)),
                     ncol = 2,
                     labels = c("(a): Western Bluebird", "(b): Tree Swallow")))
ggsave("figures/fig2_growth_by_temp_hab.png", p_full, width = 6.25, height = 4)


## --- Cort figures ---

load("data/models_cort.RData")

# Fig 4: abs cort ~ max temp x habitat (4-panel)
library(egg)
ggplot_build(fig4_tres)$layout$panel_scales_y
ggplot_build(fig4_webl)$layout$panel_scales_y
ggplot_build(fig_webl_s2)$layout$panel_scales_y
ggplot_build(fig_tres_s2)$layout$panel_scales_y
(p_full <- ggarrange(fig4_webl + ylim(0.0011, 106) + ylab("Stress-induced - Baseline corticosterone (ng/µL)") + labs(title = element_blank()) + theme(text = element_text(size = 12),
                                                                                                                                                           axis.title.x = element_blank()),
                     fig4_tres + labs(title = element_blank()) + theme(text = element_text(size = 12), axis.ticks.y = element_blank(),
                                                                                                        axis.text.y = element_blank(),
                                                                                                        axis.title.y = element_blank(),
                                                                                                        axis.title.x = element_text(hjust = 2.)),
                     fig_webl_s2 + ylim(1.3, 139) + labs(title = element_blank()) + theme(text = element_text(size = 12),
                                                                                           axis.title.x = element_blank()),
                     fig_tres_s2 + ylim(1.3, 139) + labs(title = element_blank()) + theme(text = element_text(size = 12), axis.ticks.y = element_blank(),
                                                                                           axis.text.y = element_blank(),
                                                                                           axis.title.y = element_blank(),
                                                                                           axis.title.x = element_text(hjust = 2.6)),
                     ncol = 2,
                     labels = c("(a)   Western Bluebird", "(b)   Tree Swallow", "(c)", "(d)")))
ggsave("figures/fig4_abscort_by_temp_hab.png", p_full, width = 6.25, height = 8)

# Fig S4: baseline cort ~ prior-day temp
ggplot_build(figs2_priordayt_webl)$layout$panel_scales_y
ggplot_build(figs2_priordayt_tres)$layout$panel_scales_y
(p_full <- ggarrange(figs2_priordayt_webl + ylim(0.0812, 17.9) + ylab("Baseline corticosterone (ng/µL)") + labs(title = element_blank()) + theme(text = element_text(size = 12),
                                                                                                                                                        axis.title.x = element_blank()),
                     figs2_priordayt_tres +
                       ylim(0.0812, 17.9) +
                       labs(title = element_blank()) +
                       theme(text = element_text(size = 12),
                             axis.ticks.y = element_blank(),
                             axis.text.y = element_blank(),
                             axis.title.y = element_blank(),
                             axis.title.x = element_text(hjust = -2)),
                     ncol = 2,
                     labels = c("(a): Western Bluebird", "(b): Tree Swallow")))
ggsave("figures/figs2_s1cort_by_priordayt_hab.png", p_full, width = 6.25, height = 4)

# Fig S6: TRES baseline cort ~ heat index (single panel, no assembly needed)
ggsave("figures/s1bypriordaymaxhhixhab_TRES.png", plot = figs2_priordaymaxhhi_tres, width = 10, height = 6.6)


## --- Survival figure ---

load("data/models_survival.RData")

# Fig S3: survival ~ max temp x habitat (p_full from RData is the fig3 assembly)
ggsave("figures/fig3_survival_by_temp_hab.png", p_full, width = 6.25, height = 4)


## --- Provisioning figure ---

load("data/models_provis.RData")

# Fig 5: provisioning ~ max temp x habitat (p_full from RData is the fig5 assembly)
ggsave("figures/fig5_provis_by_temp_hab.png", p_full, width = 6.25, height = 4)


## --- DAG figure ---

library(dagitty)
library(ggdag)

dag <- dagify(Growth ~ Nestling_cort + Condition + Provisioning + Humidity + Temperature + Nest_ID + Age,
              Nestling_cort ~ Site + Mother_cort + Land_cover + Provisioning + Humidity + Temperature + Brood_size + Age,
              Condition ~ Nestling_cort + Provisioning + Brood_size,
              Provisioning ~ Land_cover + Year + Mother_cort + Site + Humidity + Temperature + Brood_size + Age,
              Mother_cort ~ Site + Temperature + Nest_ID + Land_cover  + Julian_date + Brood_size + Humidity + Year,
              Temperature ~ Year + Land_cover + Julian_date + Site + Nest_ID,
              Brood_size ~ Julian_date + Temperature + Humidity + Site + Year + Nest_ID + Land_cover,
              Humidity ~ Temperature + Land_cover + Year + Julian_date + Site,
              Julian_date ~~ Land_cover,
              Julian_date ~ Site + Year,
              Nest_ID ~~ Year,
              Age ~ Nest_ID,
              Site ~ Year,
              outcome = "Growth")

(p <- ggdag_status(dag, layout = "nicely", node_size = 10) +
  geom_dag_text(colour = "black") + theme_dag_blank() + geom_dag_edges())
ggsave("figures/dag3.png", plot = p)


## --- Temp anomaly figure ---

t <- read_rds("data/temp.rds") %>%
  mutate(site = factor(str_extract(box, "([:alpha:]|[:punct:])+")),
         habitat = fct_collapse(site,
                                Orchard = c("BRO", "MCE", "PICO", "MCO", "FBFO", "PG-O-"),
                                Grassland = c("MBNG", "RRRG", "PICG", "FBFG"),
                                `Row crop` = c("MBNR", "PICR", "RRRR", "FBFR", "PG-C-", "RU-C-"),
                                Forest = c("MBNC", "PCC", "PCT", "RRC", "RRE", "SFP", "PCE")),
         habitat = factor(habitat, levels = c("Forest", "Orchard", "Grassland", "Row crop")))

wmean <- t %>%
  group_by(date, habitat, logger_position) %>%
  summarize(meanmax = mean(maxt), n = n(), .groups = "keep") %>%
  ungroup(habitat) %>%
  summarize(wmean = weighted.mean(meanmax, n)) %>%
  right_join(t, by = c("date", "logger_position")) %>%
  mutate(resid = maxt - wmean)

(out <- filter(wmean, logger_position == "O") %>%
  ggplot(mapping = aes(x = habitat, y = resid)) +
  geom_boxplot(aes(fill = habitat)) +
  xlab("Cover type") +
  ylab("Hot temperature anomaly (C)") +
  labs(title = element_blank(), fill = "Cover type") +
  annotate("text", x = c(1:4), y = 16, label = c("a", "b", "c", "d")) +
  scale_fill_viridis(discrete = TRUE) +
  theme_classic() +
  theme(text = element_text(size = 16)))
ggsave("figures/max-weightedmean_outside.png", out, width = 6, height = 4)
