# Publication figures
# Requires: data/models_*.RData (generated by model_*.R scripts)

library(tidyverse)
library(ggplot2)
library(egg)
library(ggeffects)
library(viridis)
library(scales)
library(dagitty)
library(ggdag)
library(lubridate)


## --- Growth figures ---

load("data/models_growth.RData")

# Fig S5: WEBL + TRES growth by cort x provisioning (6-panel)
(fig6_provis_webl <- predict_response(g_provis_cort_webl, terms = c("provis_mean_scaled"), bias_correction = TRUE, margin = "empirical") %>%
  plot(line_size = 1.5, alpha = .2, show_data = TRUE, limit_range = TRUE) +
  theme_classic() +
  xlab("Provisioning") +
  ylab("Growth (g/day)") +
  theme(text = element_text(size = 24)) +
  labs(title = element_blank()) +
  scale_x_continuous(
    trans = provis_trans_webl,
    breaks = c(
      (0 - mean_provis_webl) / sd_provis_webl,
      (5 - mean_provis_webl) / sd_provis_webl,
      (10 - mean_provis_webl) / sd_provis_webl,
      (15 - mean_provis_webl) / sd_provis_webl,
      (20 - mean_provis_webl) / sd_provis_webl
    )
  ) +
  theme(legend.position = "none") +
  annotate(geom = "text", label = "N = 40", x = -Inf, y = -Inf, size = 7, hjust = -.2, vjust = -.5))

(fig6_corts1_webl <- predict_response(g_provis_cort_webl, terms = c("cort_s1_scaled [all]"), bias_correction = TRUE, margin = "empirical") %>%
  plot(line_size = 1.5, alpha = .2, show_data = TRUE, limit_range = TRUE) +
  aes(linetype = .data[["group"]]) +
  theme_classic() +
  xlab("Baseline corticosterone (ng/\U00B5L)") +
  ylab("Growth (g/day)") +
  theme(text = element_text(size = 16)) +
  labs(title = element_blank()) +
  scale_x_continuous(
    trans = s1_trans_webl,
    breaks = c(
      (2 - mean_s1_webl) / sd_s1_webl,
      (4 - mean_s1_webl) / sd_s1_webl,
      (6 - mean_s1_webl) / sd_s1_webl,
      (8 - mean_s1_webl) / sd_s1_webl,
      (10 - mean_s1_webl) / sd_s1_webl,
      (12 - mean_s1_webl) / sd_s1_webl,
      (14 - mean_s1_webl) / sd_s1_webl
    )
  ) +
  scale_linetype_manual(values = "dotted") +
  theme(legend.position = "none") +
  annotate(geom = "text", label = "N = 40", x = -Inf, y = -Inf, hjust = -.2, vjust = -.5))

(fig6_abscort_webl <- predict_response(g_provis_abscort_webl, terms = c("abs_change_cort_scaled"), bias_correction = TRUE, margin = "empirical") %>%
  plot(line_size = 1.5, alpha = .2, show_data = TRUE, limit_range = TRUE) +
  aes(linetype = .data[["group"]]) +
  theme_classic() +
  xlab("Stress-induced corticosterone (ng/\U00B5L)") +
  ylab("Growth (g/day)") +
  theme(text = element_text(size = 16)) +
  labs(title = element_blank()) +
  scale_x_continuous(
    trans = abs_trans_webl,
    breaks = c(
      (0 - mean_abs_webl) / sd_abs_webl,
      (10 - mean_abs_webl) / sd_abs_webl,
      (20 - mean_abs_webl) / sd_abs_webl,
      (30 - mean_abs_webl) / sd_abs_webl,
      (40 - mean_abs_webl) / sd_abs_webl,
      (50 - mean_abs_webl) / sd_abs_webl
    )
  ) +
  scale_linetype_manual(values = "dotted") +
  theme(legend.position = "none") +
  annotate(geom = "text", label = "N = 35", x = -Inf, y = -Inf, hjust = -.2, vjust = -.5))

(fig6_provis_tres <- predict_response(g_provis_cort_tres, terms = c("provis_mean_scaled"), bias_correction = TRUE, margin = "empirical") %>%
  plot(line_size = 1.5, alpha = .2, show_data = TRUE, limit_range = TRUE) +
  aes(linetype = .data[["group"]]) +
  theme_classic() +
  xlab("Provisioning (visits/hr)") +
  ylab("Growth (g/day)") +
  theme(text = element_text(size = 16)) +
  labs(title = element_blank()) +
  scale_x_continuous(
    trans = provis_trans_tres,
    breaks = c(
      (0 - mean_provis_tres) / sd_provis_tres,
      (10 - mean_provis_tres) / sd_provis_tres,
      (20 - mean_provis_tres) / sd_provis_tres,
      (30 - mean_provis_tres) / sd_provis_tres,
      (40 - mean_provis_tres) / sd_provis_tres,
      (50 - mean_provis_tres) / sd_provis_tres
    )
  ) +
  scale_linetype_manual(values = "dotted") +
  theme(legend.position = "none") +
  annotate(geom = "text", label = "N = 16", x = -Inf, y = -Inf, hjust = -.2, vjust = -.5))

(fig6_corts1_tres <- predict_response(g_provis_cort_tres, terms = c("cort_s1_scaled [all]"), bias_correction = TRUE, margin = "empirical") %>%
  plot(line_size = 1.5, alpha = .2, show_data = TRUE, limit_range = TRUE) +
  theme_classic() +
  xlab("Baseline corticosterone (ng/\U00B5L)") +
  ylab("Growth (g/day)") +
  theme(text = element_text(size = 16)) +
  labs(title = element_blank()) +
  scale_x_continuous(
    trans = s1_trans_tres,
    breaks = c(
      (5 - mean_s1_tres) / sd_s1_tres,
      (10 - mean_s1_tres) / sd_s1_tres,
      (15 - mean_s1_tres) / sd_s1_tres,
      (20 - mean_s1_tres) / sd_s1_tres,
      (25 - mean_s1_tres) / sd_s1_tres
    )
  ) +
  theme(legend.position = "none") +
  annotate(geom = "text", label = "N = 16", x = -Inf, y = -Inf, hjust = -.2, vjust = -.5))

(fig6_abscort_tres <- predict_response(g_provis_abscort_tres, terms = c("abs_change_cort_scaled"), bias_correction = TRUE, margin = "empirical") %>%
  plot(line_size = 1.5, alpha = .2, show_data = TRUE, limit_range = TRUE) +
  aes(linetype = .data[["group"]]) +
  theme_classic() +
  xlab("Stress-induced corticosterone (ng/\U00B5L)") +
  ylab("Growth (g/day)") +
  theme(text = element_text(size = 16)) +
  labs(title = element_blank()) +
  scale_x_continuous(
    trans = abs_trans_tres,
    breaks = c(
      (20 - mean_abs_tres) / sd_abs_tres,
      (40 - mean_abs_tres) / sd_abs_tres,
      (60 - mean_abs_tres) / sd_abs_tres,
      (80 - mean_abs_tres) / sd_abs_tres,
      (100 - mean_abs_tres) / sd_abs_tres
    )
  ) +
  scale_linetype_manual(values = "dotted") +
  theme(legend.position = "none") +
  annotate(geom = "text", label = "N = 14", x = -Inf, y = -Inf, hjust = -.2, vjust = -.5))

ggplot_build(fig6_provis_webl)$layout$panel_scales_y
ggplot_build(fig6_provis_tres)$layout$panel_scales_y
ggplot_build(fig6_corts1_webl)$layout$panel_scales_y
ggplot_build(fig6_corts1_tres)$layout$panel_scales_y
ggplot_build(fig6_abscort_webl)$layout$panel_scales_y
ggplot_build(fig6_abscort_tres)$layout$panel_scales_y
(p_full <- ggarrange(
  fig6_provis_webl + theme(
    text = element_text(size = 12),
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.title.y = element_text(hjust = -3)
  ),
  fig6_provis_tres + theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    text = element_text(size = 12),
    axis.title.y = element_blank(),
    legend.position = "none",
    axis.title.x = element_text(hjust = -.7)
  ) +
    ylim(-.183, 2.73),
  fig6_corts1_webl + theme(
    text = element_text(size = 12),
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  ),
  fig6_corts1_tres + theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    text = element_text(size = 12),
    axis.title.y = element_blank(),
    legend.position = "none",
    axis.title.x = element_text(hjust = -2.7)
  ) +
    ylim(-.183, 2.73),
  fig6_abscort_webl + theme(
    text = element_text(size = 12),
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  ),
  fig6_abscort_tres + xlab("Stress-induced - Baseline corticosterone (ng/\U00B5L)") + theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    text = element_text(size = 12),
    axis.title.y = element_blank(),
    legend.position = "none",
    axis.title.x = element_text(hjust = 2.5)
  ) +
    ylim(-.183, 2.73),
  ncol = 2,
  labels = c("(a): Western Bluebird", "(b): Tree Swallow", "", "", "", "")
))
ggsave("figures/fig6_growth_by_temp_hab.png", p_full, width = 6.25, height = 8)

# Fig 2: WEBL + TRES growth ~ max temp x habitat
(fig2_tres <- ggpredict(g_lintemp_addmin_tres, terms = c("meanmaxtempI_scaled [all]", "habitat"), bias_correction = TRUE) %>%
  plot(line_size = 1.5, alpha = .2, show_data = TRUE, limit_range = TRUE) +
  aes(linetype = .data[["group"]]) +
  theme_classic() +
  facet_wrap(~group, ncol = 2) +
  xlab("Mean daily max temp over preceding week (°C)") +
  ylab("Growth (g/day)") +
  scale_fill_viridis(discrete = TRUE) +
  scale_color_viridis(discrete = TRUE) +
  scale_linetype_manual(values = c("Forest" = "dashed", "Orchard" = "dotted", "Grassland" = "solid", "Row crop" = "solid")) +
  theme(text = element_text(size = 16)) +
  labs(title = element_blank()) +
  scale_x_continuous(
    trans = temp_trans_tres,
    breaks = c(
      (20 - mean_temp_tres) / sd_temp_tres,
      (25 - mean_temp_tres) / sd_temp_tres,
      (30 - mean_temp_tres) / sd_temp_tres,
      (35 - mean_temp_tres) / sd_temp_tres,
      (40 - mean_temp_tres) / sd_temp_tres
    )
  ) +
  geom_text(data = dat_text_tres, mapping = aes(x = -Inf, y = Inf, label = label), hjust = -.2, vjust = 1.2, inherit.aes = FALSE) +
  theme(legend.position = "none"))
ggplot_build(fig2_webl)$layout$panel_scales_y
ggplot_build(fig2_tres)$layout$panel_scales_y
(p_full <- ggarrange(fig2_webl + theme(text = element_text(size = 12), axis.title.x = element_blank()),
  fig2_tres + ylim(-1.09, 3.42) + theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    text = element_text(size = 12),
    axis.title.y = element_blank(),
    axis.title.x = element_text(hjust = 2.8)
  ),
  ncol = 2,
  labels = c("(a): Western Bluebird", "(b): Tree Swallow")
))
ggsave("figures/fig2_growth_by_temp_hab.png", p_full, width = 6.25, height = 4)


## --- Cort figures ---

load("data/models_cort.RData")

# Fig 4: abs cort ~ max temp x habitat (4-panel)
library(egg)
ggplot_build(fig4_webl)$layout$panel_scales_y
ggplot_build(fig_webl_s2)$layout$panel_scales_y

(p_full <- ggarrange(
  fig4_webl + ylim(0.0065, 139) + ylab("Stress-induced - Baseline corticosterone (ng/µL)") + labs(title = element_blank()) + theme(
    text = element_text(size = 12),
    axis.title.x = element_blank(),
    plot.margin = margin(t = 20, r = 5.5, b = 5.5, l = 5.5)
  ),
  fig_webl_s2 + ylim(0.0065, 139) + labs(title = element_blank()) + theme(
    text = element_text(size = 12),
    axis.title.x = element_text(hjust = 2),
    plot.margin = margin(t = 20, r = 5.5, b = 5.5, l = 5.5)
  ),
  ncol = 2,
  labels = c("(a)   Western Bluebird", "(b)")
))

ggsave("figures/fig3_abscort_by_temp_hab.png", p_full, width = 6.25, height = 4.3)

ggplot_build(fig4_tres)$layout$panel_scales_y
ggplot_build(fig_tres_s2)$layout$panel_scales_y

(p_full <- ggarrange(
  fig4_tres + ylim(.0011, 118) + labs(title = element_blank()) + theme(
    text = element_text(size = 12),
    # axis.ticks.y = element_blank(),
    # axis.text.y = element_blank(),
    # axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    plot.margin = margin(t = 20, r = 5.5, b = 5.5, l = 5.5)
  ),
  fig_tres_s2 + ylim(.0011, 118) + labs(title = element_blank()) + theme(
    text = element_text(size = 12),
    # axis.ticks.y = element_blank(),
    # axis.text.y = element_blank(),
    # axis.title.y = element_blank(),
    axis.title.x = element_text(hjust = 2.8),
    plot.margin = margin(t = 20, r = 5.5, b = 5.5, l = 5.5)
  ),
  ncol = 2,
  labels = c("(a) Tree Swallow", "(b)")
))

ggsave("figures/figS5_abscort_by_temp_hab_tres.png", p_full, width = 6.25, height = 4.3)

# Fig S4: baseline cort ~ prior-day temp
ggplot_build(figs2_priordayt_webl)$layout$panel_scales_y
ggplot_build(figs2_priordayt_tres)$layout$panel_scales_y
(p_full <- ggarrange(
  figs2_priordayt_webl + ylim(0.0812, 17.9) + ylab("Baseline corticosterone (ng/µL)") + labs(title = element_blank()) + theme(
    text = element_text(size = 12),
    axis.title.x = element_blank()
  ),
  figs2_priordayt_tres +
    ylim(0.0812, 17.9) +
    labs(title = element_blank()) +
    theme(
      text = element_text(size = 12),
      axis.ticks.y = element_blank(),
      axis.text.y = element_blank(),
      axis.title.y = element_blank(),
      axis.title.x = element_text(hjust = -2)
    ),
  ncol = 2,
  labels = c("(a): Western Bluebird", "(b): Tree Swallow")
))
ggsave("figures/figs2_s1cort_by_priordayt_hab.png", p_full, width = 6.25, height = 4)

# Fig S6: TRES baseline cort ~ heat index (single panel, no assembly needed)
ggsave("figures/s1bypriordaymaxhhixhab_TRES.png", plot = figs2_priordaymaxhhi_tres, width = 10, height = 6.6)


## --- Survival figure ---

load("data/models_survival.RData")

# Fig S3: survival ~ max temp x habitat (p_full from RData is the fig3 assembly)
ggsave("figures/fig3_survival_by_temp_hab.png", p_full, width = 6.25, height = 4)


## --- Provisioning figure ---

load("data/models_provis.RData")

# Fig 5: provisioning ~ max temp x habitat (p_full from RData is the fig5 assembly)
ggsave("figures/fig5_provis_by_temp_hab.png", p_full, width = 6.25, height = 4)


## --- DAG figure ---

library(dagitty)
library(ggdag)

dag <- dagify(Growth_survival ~ Nestling_cort + Condition + Provisioning + Humidity + Temperature + Nest_ID + Age,
  Nestling_cort ~ Site + Mother_cort + Land_cover + Provisioning + Humidity + Temperature + Brood_size + Age,
  Condition ~ Nestling_cort + Provisioning + Brood_size,
  Provisioning ~ Land_cover + Year + Mother_cort + Site + Humidity + Temperature + Brood_size + Age,
  Mother_cort ~ Site + Temperature + Nest_ID + Land_cover + Julian_date + Brood_size + Humidity + Year,
  Temperature ~ Year + Land_cover + Julian_date + Site + Nest_ID,
  Brood_size ~ Julian_date + Temperature + Humidity + Site + Year + Nest_ID + Land_cover,
  Humidity ~ Temperature + Land_cover + Year + Julian_date + Site,
  Julian_date ~ ~Land_cover,
  Julian_date ~ Site + Year,
  Nest_ID ~ ~Year,
  Age ~ Nest_ID,
  Site ~ Year,
  outcome = "Growth_survival",
  exposure = c("Temperature", "Land_cover", "Nestling_cort", "Provisioning")
)

dag_tidy <- node_status(dag, layout = "nicely") |>
  pull_dag_data() |>
  # dagitty can't parse "/" in node names, so the outcome is relabeled here
  mutate(label = if_else(name == "Growth_survival", "Growth/survival", str_replace_all(name, "_", " ")))

layout_span <- 14 # layout size used while pulling in outliers; max_gap is relative to this
max_gap <- 3 # farthest a node may sit from its nearest neighbor, in plot units
layout_width <- 14 # final layout width in plot units (and inches in the saved figure)
layout_height <- 9 # final layout height; smaller than width makes the DAG horizontal

# Rescale layout to a 0-layout_span square so the sizes below are in predictable units
rescale_layout <- function(d) {
  rng <- range(c(d$x, d$y, d$xend, d$yend), na.rm = TRUE)
  mutate(d, across(c(x, y, xend, yend), ~ (.x - rng[1]) / diff(rng) * layout_span))
}
dag_tidy <- rescale_layout(dag_tidy)

# The layout pushes low-degree nodes far out; pull outliers in toward their nearest neighbor
node_pos <- distinct(dag_tidy, name, x, y)
nn_dist <- as.matrix(dist(node_pos[, c("x", "y")]))
diag(nn_dist) <- Inf
nn <- apply(nn_dist, 1, which.min)
shrink <- pmin(1, max_gap / apply(nn_dist, 1, min))
node_pos <- tibble(
  name = node_pos$name,
  x = node_pos$x[nn] + (node_pos$x - node_pos$x[nn]) * shrink,
  y = node_pos$y[nn] + (node_pos$y - node_pos$y[nn]) * shrink
)

# Rotate so the layout's long axis runs horizontally
node_pca <- prcomp(node_pos[, c("x", "y")])
node_pos <- node_pos |>
  mutate(x = node_pca$x[, 1], y = node_pca$x[, 2])
# PCA axis signs are arbitrary; flip if needed so the DAG reads left to right, ending at the outcome
if (node_pos$x[node_pos$name == "Growth_survival"] < 0) node_pos$x <- -node_pos$x

# Fit the layout to a layout_width x layout_height rectangle
fit_layout <- function(d) {
  x_rng <- range(c(d$x, d$xend), na.rm = TRUE)
  y_rng <- range(c(d$y, d$yend), na.rm = TRUE)
  mutate(
    d,
    across(c(x, xend), ~ (.x - x_rng[1]) / diff(x_rng) * layout_width),
    across(c(y, yend), ~ (.x - y_rng[1]) / diff(y_rng) * layout_height)
  )
}

dag_tidy <- dag_tidy |>
  dplyr::select(-x, -y, -xend, -yend) |>
  left_join(node_pos, by = "name") |>
  left_join(dplyr::rename(node_pos, to = name, xend = x, yend = y), by = "to") |>
  fit_layout()

node_text_size <- 5
node_alpha <- 0.6 # node fill opacity
node_char_width <- 0.055 # oval half-width added per label character
node_pad <- 0.2 # extra oval half-width beyond the label
node_b <- 0.3 # oval half-height
arrow_gap <- 0.1 # space between arrowheads and node edges

dag_nodes <- dag_tidy |>
  distinct(name, label, x, y, status) |>
  mutate(a = node_char_width * nchar(label) + node_pad)

# Distance from an oval's center to its edge along direction (dx, dy)
oval_radius <- function(a, b, dx, dy) {
  len <- sqrt(dx^2 + dy^2)
  1 / sqrt((dx / len / a)^2 + (dy / len / b)^2)
}

dag_edges <- dag_tidy |>
  filter(!is.na(to)) |>
  left_join(dplyr::select(dag_nodes, name, a_from = a), by = "name") |>
  left_join(dplyr::select(dag_nodes, to = name, a_to = a), by = "to") |>
  mutate(
    dx = xend - x,
    dy = yend - y,
    len = sqrt(dx^2 + dy^2),
    trim_from = oval_radius(a_from, node_b, dx, dy) + arrow_gap,
    trim_to = oval_radius(a_to, node_b, dx, dy) + arrow_gap,
    x0 = x + dx / len * trim_from,
    y0 = y + dy / len * trim_from,
    x1 = xend - dx / len * trim_to,
    y1 = yend - dy / len * trim_to
  )

(p <- ggplot() +
  geom_segment(
    data = filter(dag_edges, direction == "->"),
    aes(x = x0, y = y0, xend = x1, yend = y1),
    alpha = 0.4, arrow = arrow(length = unit(10, "pt"), type = "closed")
  ) +
  geom_segment(
    data = filter(dag_edges, direction == "<->"),
    aes(x = x0, y = y0, xend = x1, yend = y1),
    alpha = 0.4, arrow = arrow(length = unit(10, "pt"), ends = "both", type = "closed")
  ) +
  ggforce::geom_ellipse(
    data = dag_nodes,
    aes(x0 = x, y0 = y, a = a, b = node_b, angle = 0, fill = status),
    colour = NA, alpha = node_alpha
  ) +
  geom_text(data = dag_nodes, aes(x = x, y = y, label = label), size = node_text_size) +
  scale_fill_discrete(na.value = "grey50", guide = "none") +
  coord_fixed() +
  theme_dag_blank())
ggsave("figures/dag3.png", plot = p, width = layout_width, height = layout_height)


## --- Conceptual diagram ---

# Panel A: hypothesized paths (H1-H5). Panels B-G: predicted patterns for each hypothesis.
# Land cover colors match scale_fill_viridis(discrete = TRUE) in the habitat figures.

land_cover_cols <- setNames(viridis(4), c("Forest", "Orchard", "Grassland", "Row crop"))
concept_text_size <- 3.6 # geom_text size in panel A (mm)

path_nodes <- tribble(
  ~name, ~label, ~x, ~y,
  "land", "Land cover", 0.9, 2,
  "temp", "Nest box\ntemperature", 3.4, 2,
  "cort", "Nestling\ncorticosterone", 6.3, 3.4,
  "provis", "Parental\nprovisioning", 6.3, 0.6,
  "growth", "Nestling growth\n& survival", 9.2, 2
) |>
  mutate(hw = if_else(name == "growth", 0.95, 0.8), hh = 0.42) # box half-width and half-height

# Moderated = the effect of heat on this response differs among land covers
path_edges <- tribble(
  ~from, ~to, ~hyp, ~moderated,
  "land", "temp", "H1", FALSE,
  "temp", "growth", "H2", TRUE,
  "temp", "cort", "H3", TRUE,
  "temp", "provis", "H4", TRUE,
  "cort", "growth", "H5", FALSE,
  "provis", "growth", "H5", FALSE
) |>
  left_join(dplyr::select(path_nodes, from = name, x, y, hw_from = hw, hh_from = hh), by = "from") |>
  left_join(dplyr::select(path_nodes, to = name, xend = x, yend = y, hw_to = hw, hh_to = hh), by = "to") |>
  mutate(
    dx = xend - x,
    dy = yend - y,
    len = sqrt(dx^2 + dy^2),
    # distance from box center to box edge along the edge direction, plus a small gap
    trim_from = pmin(hw_from / abs(dx / len), hh_from / abs(dy / len)) + 0.08,
    trim_to = pmin(hw_to / abs(dx / len), hh_to / abs(dy / len)) + 0.08,
    x0 = x + dx / len * trim_from,
    y0 = y + dy / len * trim_from,
    x1 = xend - dx / len * trim_to,
    y1 = yend - dy / len * trim_to,
    mid_x = (x0 + x1) / 2,
    mid_y = (y0 + y1) / 2
  )

# Four-tile land cover swatch centered at (x, y)
swatch <- function(x, y, w = 0.14, h = 0.2) {
  tibble(
    xmin = x + (0:3 - 2) * w, xmax = xmin + w,
    ymin = y - h / 2, ymax = y + h / 2,
    fill = unname(land_cover_cols)
  )
}
land_node <- filter(path_nodes, name == "land")
mod_edges <- filter(path_edges, moderated)
swatches <- bind_rows(
  swatch(land_node$x, land_node$y - 0.18),
  pmap(list(mod_edges$mid_x + 0.5, mod_edges$mid_y), swatch) |> bind_rows(),
  swatch(7.9, 0.6)
)

(p_paths <- ggplot() +
  geom_segment(
    data = path_edges,
    aes(x = x0, y = y0, xend = x1, yend = y1),
    linewidth = 0.6, arrow = arrow(length = unit(7, "pt"), type = "closed")
  ) +
  geom_rect(
    data = path_nodes,
    aes(xmin = x - hw, xmax = x + hw, ymin = y - hh, ymax = y + hh),
    fill = "grey92", colour = "grey40", linewidth = 0.4
  ) +
  geom_text(
    data = filter(path_nodes, name != "land"),
    aes(x = x, y = y, label = label),
    size = concept_text_size, lineheight = 0.9
  ) +
  annotate("text", x = land_node$x, y = land_node$y + 0.15, label = land_node$label, size = concept_text_size) +
  geom_rect(
    data = swatches,
    aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = fill),
    colour = "white", linewidth = 0.3
  ) +
  geom_point(data = path_edges, aes(x = mid_x, y = mid_y), shape = 21, size = 8, fill = "white", stroke = 0.6) +
  geom_text(data = path_edges, aes(x = mid_x, y = mid_y, label = hyp), size = concept_text_size * 0.85, fontface = "bold") +
  annotate("text",
    x = 8.25, y = 0.6, hjust = 0, lineheight = 0.9, size = concept_text_size * 0.85,
    label = "Effect of heat differs\namong land covers"
  ) +
  scale_fill_identity() +
  coord_fixed(xlim = c(0, 10.3), ylim = c(0, 4), expand = FALSE) +
  theme_void())

# Stylized prediction panels: shapes only, no data or axis values
theme_prediction <- theme_classic(base_size = 10) +
  theme(
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    axis.line = element_line(arrow = arrow(length = unit(4, "pt"), type = "closed")),
    plot.title = element_text(size = 10, face = "bold"),
    legend.position = "none"
  )

heat <- seq(0, 1, length.out = 2)

# Heat effect on a response that fans out from a shared starting point, one line per land cover
heat_lines <- function(slopes, start) {
  tibble(habitat = names(land_cover_cols), slope = slopes) |>
    crossing(heat = heat) |>
    mutate(response = start + slope * heat, habitat = factor(habitat, levels = names(land_cover_cols)))
}

# Draw colored lines over a dark outline so the yellow row crop line stays visible
outlined_lines <- function(d) {
  list(
    geom_line(data = d, aes(group = habitat), colour = "grey20", linewidth = 1.9),
    geom_line(data = d, aes(colour = habitat), linewidth = 1.2)
  )
}

(p_h1 <- tibble(habitat = factor(names(land_cover_cols), levels = names(land_cover_cols)), temp = c(1, 2, 2, 3)) |>
  ggplot(aes(x = habitat, y = temp, fill = habitat)) +
  geom_col(width = 0.7, colour = "grey20", linewidth = 0.3) +
  scale_x_discrete(labels = c("Forest", "Orchard", "Grass-\nland", "Row\ncrop")) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
  scale_fill_manual(values = land_cover_cols) +
  labs(title = "H1", x = NULL, y = "Nest box temperature") +
  theme_prediction +
  theme(axis.text.x = element_text(size = 7.5)))

(p_h2 <- ggplot(mapping = aes(x = heat, y = response)) +
  outlined_lines(heat_lines(c(-0.15, -0.4, -0.47, -0.75), 0.9)) +
  scale_colour_manual(values = land_cover_cols) +
  scale_y_continuous(limits = c(0, 1)) +
  labs(title = "H2", x = "Heat", y = "Nestling growth") +
  theme_prediction +
  theme(axis.text.x = element_blank()))

# H3: cort rises and the stress-induced minus baseline difference (delta) falls more with heat in open agriculture
(p_h3_cort <- ggplot(mapping = aes(x = heat, y = response)) +
  outlined_lines(heat_lines(c(0.1, 0.23, 0.3, 0.6), 0.2)) +
  scale_colour_manual(values = land_cover_cols) +
  scale_y_continuous(limits = c(0, 1)) +
  labs(title = "H3", x = "Heat", y = "Baseline & stress-
induced cort") +
  theme_prediction +
  theme(axis.text.x = element_blank()))

(p_h3_delta <- ggplot(mapping = aes(x = heat, y = response)) +
  outlined_lines(heat_lines(c(-0.1, -0.23, -0.3, -0.6), 0.8)) +
  scale_colour_manual(values = land_cover_cols) +
  scale_y_continuous(limits = c(0, 1)) +
  labs(title = "H3", x = "Heat", y = "Δ cort") +
  theme_prediction +
  theme(axis.text.x = element_blank()))

(p_h4 <- ggplot(mapping = aes(x = heat, y = response)) +
  outlined_lines(heat_lines(c(-0.15, -0.4, -0.47, -0.75), 0.9)) +
  scale_colour_manual(values = land_cover_cols) +
  scale_y_continuous(limits = c(0, 1)) +
  labs(title = "H4", x = "Heat", y = "Provisioning") +
  theme_prediction +
  theme(axis.text.x = element_blank()))

(p_h5 <- tibble(x = heat, response = 0.15 + 0.7 * heat) |>
  ggplot(aes(x = x, y = response)) +
  geom_line(linewidth = 1.2, colour = "grey20") +
  scale_y_continuous(limits = c(0, 1)) +
  labs(title = "H5", x = "Provisioning or Δ cort", y = "Nestling growth") +
  theme_prediction +
  theme(axis.text.x = element_blank()))

# Prediction panels are wrapped as one element so they share a single tag and keep their H1-H5 titles
p_predictions <- patchwork::wrap_plots(p_h1, p_h2, p_h3_cort, p_h3_delta, p_h4, p_h5, nrow = 1) &
  theme(plot.margin = margin(14, 5.5, 5.5, 5.5)) # top margin leaves room for the (b) tag

(p_concept <- patchwork::wrap_plots(
  p_paths,
  patchwork::wrap_elements(full = p_predictions),
  ncol = 1, heights = c(1.3, 1)
) +
  patchwork::plot_annotation(tag_levels = "a", tag_prefix = "(", tag_suffix = ")"))
ggsave("figures/conceptual.png", plot = p_concept, width = 12, height = 6.5, bg = "white")


## --- Temp anomaly figure ---

t <- read_rds("data/temp.rds") %>%
  mutate(
    site = factor(str_extract(box, "([:alpha:]|[:punct:])+")),
    habitat = fct_collapse(site,
      Orchard = c("BRO", "MCE", "PICO", "MCO", "FBFO", "PG-O-"),
      Grassland = c("MBNG", "RRRG", "PICG", "FBFG"),
      `Row crop` = c("MBNR", "PICR", "RRRR", "FBFR", "PG-C-", "RU-C-"),
      Forest = c("MBNC", "PCC", "PCT", "RRC", "RRE", "SFP", "PCE")
    ),
    habitat = factor(habitat, levels = c("Forest", "Orchard", "Grassland", "Row crop"))
  )

wmean <- t %>%
  group_by(date, habitat, logger_position) %>%
  summarize(meanmax = mean(maxt), n = n(), .groups = "keep") %>%
  ungroup(habitat) %>%
  summarize(wmean = weighted.mean(meanmax, n)) %>%
  right_join(t, by = c("date", "logger_position")) %>%
  mutate(resid = maxt - wmean)

(out <- filter(wmean, logger_position == "O") %>%
  ggplot(mapping = aes(x = habitat, y = resid)) +
  geom_boxplot(aes(fill = habitat)) +
  xlab("Cover type") +
  ylab("Hot temperature anomaly (C)") +
  labs(title = element_blank(), fill = "Cover type") +
  annotate("text", x = c(1:4), y = 16, label = c("a", "b", "c", "d")) +
  scale_fill_viridis(discrete = TRUE) +
  theme_classic() +
  theme(text = element_text(size = 16)))
ggsave("figures/max-weightedmean_outside.png", out, width = 6, height = 4)
