---
title: "Triglycerides exploration"
author: "Katherine Lauck"
date: "2024-09-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
d <- read_rds("../data/trigly_with_id.rds") %>% 
  filter(!is.na(sample_occ))

g <- read_rds("../data/growth.rds")
```

## Is triglyceride concentration correlated with cort?

```{r}
plot(trigly_conc~mean_s1, data = filter(d, sample_occ == "S1"))
plot(trigly_conc~mean_s2, data = filter(d, sample_occ != "S1"))

summary(lm(trigly_conc~condition, data = filter(d, condition < 1.6)))
plot(trigly_conc~condition, data = filter(d,condition < 1.6))

d$d1_trigly_conc <- (d$absorbance_d1 - 0.0590 - d$std_intercept) / d$std_slope 
d$cort_dif <- d$mean_s2-d$mean_s1

summary(lm(d1_trigly_conc~condition, data = filter(d, condition < 1.6)))
plot(d1_trigly_conc~condition, data = filter(d, condition < 1.6))


summary(lm(condition ~ condition_mother + habitat, data = filter(g, occasion == 3,Species == "WEBL")))
summary(lm(condition ~ habitat, data = filter(g, occasion ==3, Species == "WEBL")))

boxplot(condition ~ habitat, data = filter(g, occasion ==3, Species == "WEBL"))
boxplot(condition ~ habitat, data = g)

g %>% filter(occasion == 3, !is.na(cort_s2), Species == "WEBL") %>% group_by(c(habitat)) %>% summarize(n = n())

summary(lm(d1_trigly_conc~mean_s2, data = d))
plot(d1_trigly_conc~mean_s2, data = d)

summary(lm(d1_trigly_conc~cort_dif, data = d))
plot(d1_trigly_conc~cort_dif, data = d)

```

```{r}

```

